CourseWork/CourseWork.Web/Models/Item/ItemViewModel.cs
using CourseWork.Core;
using CourseWork.Core.AdditionalFields;
using CourseWork.Core.UsersActivity;
using System.Collections.Generic;

namespace CourseWork.Web.Models.Item
{
    public class ItemViewModel
    {
        public ItemViewModel()
        {
            Id = 0;
            Name = string.Empty;
            Fields = new List<IAdditionalField>();
            Tags = new List<Tag>();
            Likes = 0;
            Comments = new List<UserCommentViewModel>();
        }

        public int Id { get; set; }

        public string Name { get; set; }

        public List<IAdditionalField> Fields { get; set; }

        public List<Tag> Tags { get; set; }

        public int Likes { get; set; }

        public List<UserCommentViewModel> Comments { get; set; }
    }
}

CourseWork/CourseWork.Web/Models/Item/UserCommentViewModel.cs
using CourseWork.Core.Identity;
using CourseWork.Core.UsersActivity;
using System;

namespace CourseWork.Web.Models.Item
{
    public class UserCommentViewModel
    {
        public UserCommentViewModel()
        {
            Username = string.Empty;
            Date = new DateTime(1980, 1, 1);
            Text = string.Empty;
        }

        public UserCommentViewModel(WebUser user, UserComment comment)
        {
            Username = user.UserName;
            Date = comment.Date;
            Text = comment.Text;
        }

        public string Username { get; set; }

        public DateTime Date { get; set; }

        public string Text { get; set; }
    }
}

CourseWork/CourseWork.Web/Models/Items/EditItemViewModel.cs
using CourseWork.Core;
using CourseWork.Core.AdditionalFields;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CourseWork.Web.Models.Items
{
    public class EditItemViewModel
    {
        public EditItemViewModel(CollectionItem item, IEnumerable<IAdditionalField> fields)
        {

        }
    }
}

CourseWork/CourseWork.Web/Models/Items/ItemViewModel.cs
using CourseWork.Core.AdditionalFields;
using System.Collections.Generic;

namespace CourseWork.Web.Models.Items
{
    public class ItemViewModel
    {
        public ItemViewModel()
        {
            Id = 0;
            Name = string.Empty;
            Likes = 0;
            Comments = 0;
        }

        public int Id { get; set; }

        public string Name { get; set; }

        public int Likes { get; set; }

        public int Comments { get; set; }
    }
}

CourseWork/CourseWork.Web/Models/Items/ItemsViewModel.cs
using System.Collections.Generic;

namespace CourseWork.Web.Models.Items
{
    public class ItemsViewModel
    {
        public ItemsViewModel()
        {
            CollectionId = 0;
            Items = new List<ItemViewModel>();
            Fields = new List<string>();
        }

        public int CollectionId { get; set; }

        public List<ItemViewModel> Items { get; set; }

        public List<string> Fields { get; set; }
    }
}

CourseWork/CourseWork.Web/Controllers/ItemController.cs
using CourseWork.BusinessLogic.Services;
using CourseWork.BusinessLogic.StaticServices;
using CourseWork.Core;
using CourseWork.Core.Identity;
using CourseWork.Web.Models.Item;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CourseWork.Web.Controllers
{
    public class ItemController : Controller
    {
        private readonly UserActivityService _userActivityService;
        private readonly ItemFieldsService _itemFieldsService;
        private readonly UserManager<WebUser> _userManager;
        private readonly IService<CollectionItem> _collectionItemService;
        private readonly IService<Tag> _tagService;

        public ItemController(UserActivityService userActivityService,
            ItemFieldsService itemFieldsService,
            UserManager<WebUser> userManager,
            IService<CollectionItem> collectionItemService,
            IService<Tag> tagService)
        {
            _userActivityService = userActivityService;
            _itemFieldsService = itemFieldsService;
            _userManager = userManager;
            _collectionItemService = collectionItemService;
            _tagService = tagService;
        }

        public async Task<IActionResult> Index(int itemId)
        {
            var items = await _collectionItemService.SelectAsync();
            var likes = await _userActivityService.GetLikes();
            var comments = await _userActivityService.GetComments();
            var tags = await _tagService.SelectAsync();
            var fields = await _itemFieldsService.GetItemFields(itemId);
            if (!items.Successfully
                || !likes.Successfully
                || !comments.Successfully
                || !tags.Successfully
                || !fields.Successfully)
            {
                return BadRequest();
            }

            List<UserCommentViewModel> commentsView = new List<UserCommentViewModel>();
            foreach (var comment in comments.Value.Where(c => c.CollectionItemId == itemId))
            {
                var user = await _userManager.FindByIdAsync(comment.UserId);
                commentsView.Add(new UserCommentViewModel(user, comment));
            }
            return View(new ItemViewModel
            {
                Id = itemId,
                Likes = likes.Value.Count(l => l.CollectionItemId == itemId),
                Name = items.Value.First(i => i.Id == itemId).Name,
                Comments = commentsView,
                Fields = fields.Value.ToList(),
                Tags = tags.Value.Where(t => t.CollectionItemId == itemId).ToList(),
            });
        }

        [Authorize]
        public async Task<IActionResult> Like(int itemId)
        {
            WebUser user = await _userManager.GetUserAsync(User);
            var res = await _userActivityService.AddLike(user, itemId);
            if (!res.Successfully)
            {
                return BadRequest();
            }

            return RedirectToAction(nameof(Index), new { itemId = itemId });
        }

        [Authorize]
        public async Task<IActionResult> Comment(int itemId, string commentText)
        {
            WebUser user = await _userManager.GetUserAsync(User);
            var res = await _userActivityService.AddComment(user, itemId, commentText);
            if (!res.Successfully)
            {
                return BadRequest();
            }

            return RedirectToAction(nameof(Index), new { itemId = itemId });
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> AddTag(int itemId, string tagName)
        {
            var res = await _tagService.InsertAsync(new Tag(0, tagName, itemId));

            return RedirectToAction(nameof(Index), new { itemId = itemId });
        }
    }
}

CourseWork/CourseWork.Web/Controllers/ItemsController.cs
using CourseWork.BusinessLogic.Services;
using CourseWork.BusinessLogic.StaticServices;
using CourseWork.Core;
using CourseWork.Web.Models.Items;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CourseWork.Web.Controllers
{
    public class ItemsController : Controller
    {
        private readonly SearchItemService _searchService;
        private readonly UserActivityService _userActivityService;
        private readonly ItemFieldsService _itemFieldsService;
        private readonly IService<CollectionItem> _itemService;
        private readonly IService<CollectionRequiredFields> _requiredFieldsService;

        public ItemsController(SearchItemService searchService,
            UserActivityService userActivityService,
            ItemFieldsService itemFieldsService,
            IService<CollectionItem> itemService,
            IService<CollectionRequiredFields> requiredFieldsService)
        {
            _searchService = searchService;
            _userActivityService = userActivityService;
            _itemFieldsService = itemFieldsService;
            _itemService = itemService;
            _requiredFieldsService = requiredFieldsService;
        }

        public async Task<IActionResult> Index(int collectionId = 0, string searchString = null)
        {
            ItemsViewModel model = new ItemsViewModel();
            IEnumerable<CollectionItem> items = new List<CollectionItem>();
            if (collectionId != 0 && string.IsNullOrEmpty(searchString))
            {
                var serviceRes = await _itemService.SelectAsync();
                var fieldsRes = await _requiredFieldsService.SelectAsync();
                if (!serviceRes.Successfully || !fieldsRes.Successfully)
                {
                    return BadRequest();
                }
                items = serviceRes.Value.Where(i => i.CollectionId == collectionId);
                model.CollectionId = collectionId;
                model.Fields = fieldsRes.Value.First(f => f.CollectionId == collectionId).GetSpecifiedFields();
            }
            else if (collectionId == 0 && !string.IsNullOrEmpty(searchString))
            {
                var serviceRes = await _searchService.SearchItems(searchString);
                if (!serviceRes.Successfully)
                {
                    return BadRequest();
                }
                items = serviceRes.Value;
                model.Fields = new List<string>();
            }

            var likesRes = await _userActivityService.GetLikes();
            var commentsRes = await _userActivityService.GetComments();
            if (!likesRes.Successfully || !commentsRes.Successfully)
            {
                return BadRequest();
            }

            model.Items = items.Select(i => new ItemViewModel
            {
                Id = i.Id,
                Name = i.Name,
                Comments = commentsRes.Value.Count(c => c.CollectionItemId == i.Id),
                Likes = likesRes.Value.Count(l => l.CollectionItemId == i.Id),
            }).ToList();

            return View(model);
        }

        public IActionResult CantCreate()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Create(int collectionId)
        {
            if (collectionId == 0)
            {
                return LocalRedirect("~/Collections/Index");
            }
            var fields = await _requiredFieldsService.SelectAsync();
            if (!fields.Successfully)
            {
                return RedirectToAction(nameof(Index), new { collectionId = collectionId });
            }

            return View(new CreateItemViewModel(collectionId, fields.Value.First(f => f.CollectionId == collectionId)));
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind] CreateItemViewModel viewModel)
        {
            var item = new CollectionItem(0, viewModel.CollectionId, viewModel.Name);
            var itemRes = await _itemService.InsertAsync(item);
            if (!itemRes.Successfully)
            {
                return BadRequest();
            }
            var fields = viewModel.GetFields(item.Id);
            var fieldsRes = await _itemFieldsService.AddFields(item.Id, fields);

            if (!fieldsRes.Successfully)
            {
                return BadRequest();
            }

            return RedirectToAction(nameof(Index), new { collectionId = viewModel.CollectionId });
        }

        public async Task<IActionResult> DeleteItem(int itemId, string returnUrl)
        {
            var items = await _itemService.SelectAsync();
            if (!items.Successfully)
                return BadRequest();

            var item = items.Value.FirstOrDefault(i => i.Id == itemId);
            if (item == default)
                return BadRequest();

            var res = await _itemService.DeleteAsync(item);
            return LocalRedirect(returnUrl);
        }
    }
}

CourseWork/CourseWork.Web/Views/Items/Create.cshtml
@model CourseWork.Web.Models.Items.CreateItemViewModel
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer

<div class="container mt-5">
    <div class="row justify-content-center align-items-center">
        <div class="col-sm-12 col-mb-12 col-lg-4">
            <form asp-controller="Items" asp-action="Create" method="post">
                <h3 class="mb-3">@Localizer["ViewTitle"]</h3>
                <input asp-for="@Model.CollectionId" type="hidden" />

                <div class="form-group">
                    <label class="form-label" asp-for="@Model.Name">@Localizer["Title"]</label>
                    <input type="text" asp-for="@Model.Name" class="form-control" />
                    <span asp-validation-for="@Model.Name" class="text-danger"></span>
                </div>

                @if (Model.Boolean1FieldRequired)
                {
                    <input asp-for="@Model.Boolean1FieldRequired" type="hidden" />
                    <div class="form-group">
                        <label class="form-label" asp-for="@Model.Boolean1FieldName">@Model.Boolean1FieldName</label>
                        <input asp-for="@Model.Boolean1FieldName" type="hidden" />
                        <input type="checkbox" asp-for="@Model.Boolean1FieldValue" class="form-control" />
                    </div>
                }
                @if (Model.Boolean2FieldRequired)
                {
                    <input asp-for="@Model.Boolean2FieldRequired" type="hidden" />
                    <div class="form-group">
                        <label class="form-label" asp-for="@Model.Boolean2FieldName">@Model.Boolean2FieldName</label>
                        <input asp-for="@Model.Boolean2FieldName" type="hidden" />
                        <input type="checkbox" asp-for="@Model.Boolean2FieldValue" class="form-control" />
                    </div>
                }
                @if (Model.Boolean3FieldRequired)
                {
                    <input asp-for="@Model.Boolean3FieldRequired" type="hidden" />
                    <div class="form-group">
                        <label class="form-label" asp-for="@Model.Boolean3FieldName">@Model.Boolean3FieldName</label>
                        <input asp-for="@Model.Boolean3FieldName" type="hidden" />
                        <input type="checkbox" asp-for="@Model.Boolean3FieldValue" class="form-control" />
                    </div>
                }

                @if (Model.Date1FieldRequired)
                {
                    <input asp-for="@Model.Date1FieldRequired" type="hidden" />
                    <div class="form-group">
                        <label class="form-label" asp-for="@Model.Date1FieldName">@Model.Date1FieldName</label>
                        <input asp-for="@Model.Date1FieldName" type="hidden" />
                        <input type="datetime" asp-for="@Model.Date1FieldValue" class="form-control" />
                    </div>
                }
                @if (Model.Date2FieldRequired)
                {
                    <input asp-for="@Model.Date2FieldRequired" type="hidden" />
                    <div class="form-group">
                        <label class="form-label" asp-for="@Model.Date2FieldName">@Model.Date2FieldName</label>
                        <input asp-for="@Model.Date2FieldName" type="hidden" />
                        <input type="datetime" asp-for="@Model.Date2FieldValue" class="form-control" />
                    </div>
                }
                @if (Model.Date3FieldRequired)
                {
                    <input asp-for="@Model.Date3FieldRequired" type="hidden" />
                    <div class="form-group">
                        <label class="form-label" asp-for="@Model.Date3FieldName">@Model.Date3FieldName</label>
                        <input asp-for="@Model.Date3FieldName" type="hidden" />
                        <input type="datetime" asp-for="@Model.Date3FieldValue" class="form-control" />
                    </div>
                }

                @if (Model.Int1FieldRequired)
                {
                    <input asp-for="@Model.Int1FieldRequired" type="hidden" />
                    <div class="form-group">
                        <label class="form-label" asp-for="@Model.Int1FieldName">@Model.Int1FieldName</label>
                        <input asp-for="@Model.Int1FieldName" type="hidden" />
                        <input type="datetime" asp-for="@Model.Int1FieldValue" class="form-control" />
                    </div>
                }
                @if (Model.Int2FieldRequired)
                {
                    <input asp-for="@Model.Int2FieldRequired" type="hidden" />
                    <div class="form-group">
                        <label class="form-label" asp-for="@Model.Int2FieldName">@Model.Int2FieldName</label>
                        <input asp-for="@Model.Int2FieldName" type="hidden" />
                        <input type="datetime" asp-for="@Model.Int2FieldValue" class="form-control" />
                    </div>
                }
                @if (Model.Int3FieldRequired)
                {
                    <input asp-for="@Model.Int3FieldRequired" type="hidden" />
                    <div class="form-group">
                        <label class="form-label" asp-for="@Model.Int3FieldName">@Model.Int3FieldName</label>
                        <input asp-for="@Model.Int3FieldName" type="hidden" />
                        <input type="datetime" asp-for="@Model.Int3FieldValue" class="form-control" />
                    </div>
                }

                @if (Model.String1FieldRequired)
                {
                    <input asp-for="@Model.String1FieldRequired" type="hidden" />
                    <div class="form-group">
                        <label class="form-label" asp-for="@Model.String1FieldName">@Model.String1FieldName</label>
                        <input asp-for="@Model.String1FieldName" type="hidden" />
                        <input type="datetime" asp-for="@Model.String1FieldValue" class="form-control" />
                    </div>
                }
                @if (Model.String2FieldRequired)
                {
                    <input asp-for="@Model.String2FieldRequired" type="hidden" />
                    <div class="form-group">
                        <label class="form-label" asp-for="@Model.String2FieldName">@Model.String2FieldName</label>
                        <input asp-for="@Model.String2FieldName" type="hidden" />
                        <input type="datetime" asp-for="@Model.String2FieldValue" class="form-control" />
                    </div>
                }
                @if (Model.String3FieldRequired)
                {
                    <input asp-for="@Model.String3FieldRequired" type="hidden" />
                    <div class="form-group">
                        <label class="form-label" asp-for="@Model.String3FieldName">@Model.String3FieldName</label>
                        <input asp-for="@Model.String3FieldName" type="hidden" />
                        <input type="datetime" asp-for="@Model.String3FieldValue" class="form-control" />
                    </div>
                }

                @if (Model.Text1FieldRequired)
                {
                    <input asp-for="@Model.Text1FieldRequired" type="hidden" />
                    <div class="form-group">
                        <label class="form-label" asp-for="@Model.Text1FieldName">@Model.Text1FieldName</label>
                        <input asp-for="@Model.Text1FieldName" type="hidden" />
                        <input type="datetime" asp-for="@Model.Text1FieldValue" class="form-control" />
                    </div>
                }
                @if (Model.Text2FieldRequired)
                {
                    <input asp-for="@Model.Text2FieldRequired" type="hidden" />
                    <div class="form-group">
                        <label class="form-label" asp-for="@Model.Text2FieldName">@Model.Text2FieldName</label>
                        <input asp-for="@Model.Text2FieldName" type="hidden" />
                        <input type="datetime" asp-for="@Model.Text2FieldValue" class="form-control" />
                    </div>
                }
                @if (Model.Text3FieldRequired)
                {
                    <input asp-for="@Model.Text3FieldRequired" type="hidden" />
                    <div class="form-group">
                        <label class="form-label" asp-for="@Model.Text3FieldName">@Model.Text3FieldName</label>
                        <input asp-for="@Model.Text3FieldName" type="hidden" />
                        <input type="datetime" asp-for="@Model.Text3FieldValue" class="form-control" />
                    </div>
                }
                <button type="submit" class="btn btn-primary">@Localizer["Create"]</button>
            </form>
        </div>
    </div>
</div>

CourseWork/CourseWork.Web/Views/Items/Edit.cshtml
@model CourseWork.Web.Models.Items.EditItemViewModel
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer

CourseWork/CourseWork.Web/Views/Items/Index.cshtml
@model CourseWork.Web.Models.Items.ItemsViewModel
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer

<div>
    <div class="row">
        <div class="col-6">@await Html.PartialAsync("_ItemSearch")</div>
        <div class="col-6"><a class="btn btn-primary" asp-controller="Items" asp-action="Create" asp-route-collectionId="@Model.CollectionId">@Localizer["Create"]</a></div>
    </div>
    <div class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item m-1">@Localizer["Fields"]</li>
                @foreach (var field in Model.Fields)
                {
                    <li class="nav-item m-1">@Html.DisplayFor(view => field)</li>
                }
            </ul>
        </div>
    </div>
    @foreach (var item in Model.Items)
    {
        <a class="list-group-item list-group-item-action flex-column align-items-start"
           asp-controller="Item" asp-action="Index" asp-route-itemId="@item.Id">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">@Html.DisplayFor(view => item.Name)</h5>
            </div>

            <div class="d-flex w-100 justify-content-between">
                <small>@Localizer["Likes"] @Html.DisplayFor(view => @item.Likes)</small>
                <small>@Localizer["Comments"] @Html.DisplayFor(view => item.Comments)</small>
            </div>
        </a>
        <a asp-controller="Items" asp-action="DeleteItem" asp-route-itemId="@item.Id" asp-route-returnUrl="@Context.Request.Path">@Localizer["Delete"]</a>
    }
</div>