CourseWork/CourseWork.Web/Models/Shared/ErrorViewModel.cs
namespace CourseWork.Web.Models.Shared
{
    public class ErrorViewModel
    {
        public ErrorViewModel()
        {
            RequestId = string.Empty;
        }

        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CourseWork/CourseWork.Web/Controllers/ItemsController.cs
using CourseWork.BusinessLogic.Services;
using CourseWork.BusinessLogic.StaticServices;
using CourseWork.Core;
using CourseWork.Web.Models.Items;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CourseWork.Web.Controllers
{
    public class ItemsController : Controller
    {
        private readonly SearchItemService _searchService;
        private readonly UserActivityService _userActivityService;
        private readonly ItemFieldsService _itemFieldsService;
        private readonly IService<CollectionItem> _itemService;
        private readonly IService<CollectionRequiredFields> _requiredFieldsService;

        public ItemsController(SearchItemService searchService,
            UserActivityService userActivityService,
            ItemFieldsService itemFieldsService,
            IService<CollectionItem> itemService,
            IService<CollectionRequiredFields> requiredFieldsService)
        {
            _searchService = searchService;
            _userActivityService = userActivityService;
            _itemFieldsService = itemFieldsService;
            _itemService = itemService;
            _requiredFieldsService = requiredFieldsService;
        }

        public async Task<IActionResult> Index(int collectionId = 0, string searchString = null)
        {
            ItemsViewModel model = new ItemsViewModel();
            IEnumerable<CollectionItem> items = new List<CollectionItem>();
            if (collectionId != 0 && string.IsNullOrEmpty(searchString))
            {
                var serviceRes = await _itemService.SelectAsync();
                var fieldsRes = await _requiredFieldsService.SelectAsync();
                if (!serviceRes.Successfully || !fieldsRes.Successfully)
                {
                    return BadRequest();
                }
                items = serviceRes.Value.Where(i => i.CollectionId == collectionId);
                model.CollectionId = collectionId;
                model.Fields = fieldsRes.Value.First(f => f.CollectionId == collectionId).GetSpecifiedFields();
            }
            else if (collectionId == 0 && !string.IsNullOrEmpty(searchString))
            {
                var serviceRes = await _searchService.SearchItems(searchString);
                if (!serviceRes.Successfully)
                {
                    return BadRequest();
                }
                items = serviceRes.Value;
                model.Fields = new List<string>();
            }

            var likesRes = await _userActivityService.GetLikes();
            var commentsRes = await _userActivityService.GetComments();
            if (!likesRes.Successfully || !commentsRes.Successfully)
            {
                return BadRequest();
            }

            model.Items = items.Select(i => new ItemViewModel
            {
                Id = i.Id,
                Name = i.Name,
                Comments = commentsRes.Value.Count(c => c.CollectionItemId == i.Id),
                Likes = likesRes.Value.Count(l => l.CollectionItemId == i.Id),
            }).ToList();

            return View(model);
        }

        public IActionResult CantCreate()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Create(int collectionId)
        {
            if (collectionId == 0)
            {
                return LocalRedirect("~/Collections/Index");
            }
            var fields = await _requiredFieldsService.SelectAsync();
            if (!fields.Successfully)
            {
                return RedirectToAction(nameof(Index), new { collectionId = collectionId });
            }

            return View(new CreateItemViewModel(collectionId, fields.Value.First(f => f.CollectionId == collectionId)));
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind] CreateItemViewModel viewModel)
        {
            var item = new CollectionItem(0, viewModel.CollectionId, viewModel.Name);
            var itemRes = await _itemService.InsertAsync(item);
            if (!itemRes.Successfully)
            {
                return BadRequest();
            }
            var fields = viewModel.GetFields(item.Id);
            var fieldsRes = await _itemFieldsService.AddFields(item.Id, fields);

            if (!fieldsRes.Successfully)
            {
                return BadRequest();
            }

            return RedirectToAction(nameof(Index), new { collectionId = viewModel.CollectionId });
        }

        public async Task<IActionResult> DeleteItem(int itemId, string returnUrl)
        {
            var items = await _itemService.SelectAsync();
            if (!items.Successfully)
                return BadRequest();

            var item = items.Value.FirstOrDefault(i => i.Id == itemId);
            if (item == default)
                return BadRequest();

            var res = await _itemService.DeleteAsync(item);
            return LocalRedirect(returnUrl);
        }
    }
}

CourseWork/CourseWork.Web/Controllers/ProfileController.cs
using CourseWork.Core.Identity;
using CourseWork.Web.Models.Profile;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace CourseWork.Web.Controllers
{
    public class ProfileController : Controller
    {
        private readonly RoleManager<WebRole> _roleManager;
        private readonly UserManager<WebUser> _userManager;
        private readonly SignInManager<WebUser> _signInManager;

        public ProfileController(RoleManager<WebRole> roleManager,
            UserManager<WebUser> userManager,
            SignInManager<WebUser> signInManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            return View(new ProfileViewModel(user));
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login([Bind] LoginViewModel viewModel, string returnUrl = null)
        {
            if (ModelState.IsValid)
            {
                var res = await _signInManager.PasswordSignInAsync(viewModel.UserName,
                    viewModel.Password, viewModel.RememberMe, false);

                if (res.Succeeded)
                {
                    return returnUrl == null || returnUrl == "/"
                        ? RedirectToAction(nameof(Index))
                        : RedirectToAction(returnUrl);
                }

                ModelState.AddModelError("", "Username or password incorrect.");
            }

            return View();
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register([Bind] RegisterViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var user = new WebUser
                {
                    FirstName = viewModel.FirstName,
                    SecondName = viewModel.SecondName,
                    UserName = viewModel.UserName,
                };

                var res = await _userManager.CreateAsync(user, viewModel.Password);
                if (res.Succeeded)
                {
                    await _signInManager.SignInAsync(user, false);
                    return RedirectToAction(nameof(Index));
                }

                foreach (var error in res.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }

            return View();
        }


        [HttpGet]
        public IActionResult Logout()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> LogoutUser()
        {
            await _signInManager.SignOutAsync();
            return LocalRedirect("~/Home/Index");
        }

        [HttpPost]
        public IActionResult DongLogoutUser()
        {
            return LocalRedirect("~/Home/Index");
        }
    }
}

CourseWork/CourseWork.Web/Controllers/RolesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CourseWork.Core.Identity;
using CourseWork.Web.Models.Roles;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CourseWork.Web.Controllers
{
    public class RolesController : Controller
    {
        private readonly RoleManager<WebRole> _roleManager;
        private readonly UserManager<WebUser> _userManager;

        public RolesController(RoleManager<WebRole> roleManager, UserManager<WebUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        [HttpGet]
        public IActionResult Index() => View(_roleManager.Roles.ToList());

        [HttpGet]
        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Name")] CreateRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                IdentityResult res = await _roleManager.CreateAsync(new WebRole { Name = model.Name });

                if (res.Succeeded)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    foreach (var error in res.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }

            return View(model);
        }

        public async Task<IActionResult> Delete(string id)
        {
            WebRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                await _roleManager.DeleteAsync(role);
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult UserList() => View(_userManager.Users.ToList());

        [HttpGet]
        public async Task<IActionResult> Edit(string userId)
        {
            WebUser user = await _userManager.FindByIdAsync(userId);

            if (user != null)
            {
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();

                ChangeRoleViewModel viewModel = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserName = user.UserName,
                    UserRoles = userRoles,
                    AllRoles = allRoles,
                };
                return View(viewModel);
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            WebUser user = await _userManager.FindByIdAsync(userId);

            if (user != null)
            {
                var userRoles = await _userManager.GetRolesAsync(user);
                var addedRoles = roles.Except(userRoles);
                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);
                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction(nameof(UserList));
            }

            return NotFound();
        }
    }
}

CourseWork/CourseWork.Web/Controllers/TagsController.cs
using CourseWork.BusinessLogic.Services;
using CourseWork.Core;
using CourseWork.Web.Models.Tags;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace CourseWork.Web.Controllers
{
    [Authorize]
    public class TagsController : Controller
    {
        private readonly IService<Tag> _tagsService;

        public TagsController(IService<Tag> tagsService)
        {
            _tagsService = tagsService;
        }

        public async Task<IActionResult> Index()
        {
            var res = await _tagsService.SelectAsync();
            if (!res.Successfully)
                return BadRequest();
            return View(new TagsViewModel
            {
                Tags = res.Value.ToList(),
            });
        }
    }
}

CourseWork/CourseWork.Web/Views/Shared/_ItemSearch.cshtml
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer

<form asp-controller="Items" asp-action="Index">
    <p>
        @Localizer["Search"] <input type="text" name="searchString"/>
        <input type="submit" value="@Localizer["Button"]"/>
    </p>
</form>

CourseWork/CourseWork.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity 
@inject SignInManager<CourseWork.Core.Identity.WebUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CourseWork.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CourseWork.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Collections" asp-action="Index">Collections</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Tags" asp-action="Index">Tags</a>
                            </li>
                        </ul>
                        <ul class="navbar-nav d-flex justify-content-end flex-grow-1">
                            <li class="nav-item">
                                <a asp-area="" asp-controller="Profile" asp-action="Index" class="btn btn-primary">Profile</a>
                            </li>
                            <li class="nav-item ml-1">
                                <a asp-area="" asp-controller="Profile" asp-action="Logout" class="btn btn-secondary">Logout</a>
                            </li>
                        </ul>
                    }
                    else
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Collections" asp-action="Index">Collections</a>
                            </li>
                        </ul>
                        <ul class="navbar-nav d-flex justify-content-end flex-grow-1">
                            <li class="nav-item">
                                <a asp-area="" asp-controller="Profile" asp-action="Login" class="btn btn-primary">Login</a>
                            </li>
                            <li class="nav-item">
                                <a asp-area="" asp-controller="Profile" asp-action="Register" class="btn">Register</a>
                            </li>
                        </ul>
                    }
                    @await Html.PartialAsync("_SelectLanguagePartial")
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CourseWork.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            @if (SignInManager.IsSignedIn(User) && User.IsInRole("admin"))
            {
                <a asp-area="" asp-controller="Roles" asp-action="Index">Roles</a>
            }
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CourseWork/CourseWork.Web/Views/Shared/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.NativeName })
        .ToList();
}

<form asp-controller="Home" asp-action="SetLanguage" style="margin-top:20px;"
      asp-route-returnUrl="@Context.Request.Path"
      method="post" class="form-horizontal">
    Language: <select name="culture" onchange="this.form.submit();"
                      asp-for="@requestCulture.RequestCulture.UICulture.Name"
                      asp-items="cultureItems"></select>
</form>