WebTask/WebTask.Api/Models/Users/UsersViewModel.cs
using System.Collections.Generic;
using WebTask.Api.Core;

namespace WebTask.Api.Models.Users
{
    public class UsersViewModel
    {
        public IEnumerable<WebUser> Users { get; set; }
    }
}

WebTask/WebTask.Api/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebTask.Api.Core;
using WebTask.Api.Models.Users;

namespace WebTask.Api.Controllers
{
    public class UsersController : Controller
    {
        private readonly UserManager<WebUser> _userManager;
        private readonly SignInManager<WebUser> _signInManager;

        public UsersController(UserManager<WebUser> userManager,
            SignInManager<WebUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        public IActionResult Index()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return LocalRedirect("~/Account/Login");
            }

            var viewModel = new UsersViewModel
            {
                Users = _userManager.Users.ToList(),
            };

            return View(viewModel);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Block(List<string> selectedUsers)
        {
            var currentUser = await _userManager.GetUserAsync(User);
            foreach (var userId in selectedUsers)
            {
                var user = await _userManager.FindByIdAsync(userId);
                user.Status = 1;
                user.LockoutEnabled = true;
                user.LockoutEnd = System.DateTimeOffset.Now.AddDays(36_135.0);
                await _userManager.UpdateAsync(user);
                if (user.Id == currentUser.Id)
                {
                    await _signInManager.SignOutAsync();
                }
            }

            return RedirectToAction(nameof(Index));
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Unblock(List<string> selectedUsers)
        {
            foreach (var userId in selectedUsers)
            {
                var user = await _userManager.FindByIdAsync(userId);
                user.Status = 0;
                user.LockoutEnabled = false;
                user.LockoutEnd = null;
                await _userManager.UpdateAsync(user);
            }

            return RedirectToAction(nameof(Index));
        }
        
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Delete(List<string> selectedUsers)
        {
            var currentUser = await _userManager.GetUserAsync(User);
            bool signOut = false;
            foreach (var userId in selectedUsers)
            {
                var user = await _userManager.FindByIdAsync(userId);
                if (user.Id == currentUser.Id) signOut = true;
                await _userManager.DeleteAsync(user);
            }
            if (signOut)
            {
                await _signInManager.SignOutAsync();
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

WebTask/WebTask.Api/Views/Users/Index.cshtml
@model WebTask.Api.Models.Users.UsersViewModel

<form id='form1' method="post">
    <button type="submit" class="btn-primary" asp-controller="Users" asp-action="Block">Block</button>
    <button type="submit" class="btn-secondary" asp-controller="Users" asp-action="Unblock">Unblock</button>
    <button type="submit" class="btn-danger" asp-controller="Users" asp-action="Delete">Delete</button>

    <table class="table table-bordered table-checks">
        <tr>
            <th><input type="checkbox" name="cb_all"></th>
            <th>Username</th>
            <th>Email</th>
            <th>Registration Date</th>
            <th>Last Login</th>
            <th>Status</th>
        </tr>
        @foreach (var user in Model.Users)
        {
            <tr>
                <td><input type="checkbox" class="qwe" name="selectedUsers" value="@user.Id" /></td>
                <td>@Html.DisplayFor(item => user.UserName)</td>
                <td>@Html.DisplayFor(item => user.Email)</td>
                <td>@Html.DisplayFor(item => user.RegistrationDate)</td>
                <td>@Html.DisplayFor(item => user.LastLoginDate)</td>
                <td>@Html.DisplayFor(item => user.StatusString)</td>
            </tr>
        }
    </table>
</form>
<script>
    var f = document.getElementById('form1');
    f.cb_all.onchange = function (e) {
        var el = e.target || e.srcElement;
        var qwe = el.form.getElementsByClassName('qwe');
        for (var i = 0; i < qwe.length; i++) {
            if (el.checked) {
                qwe[i].checked = true;
            } else {
                qwe[i].checked = false;
            }
        }
    }
</script>