CourseWork/CourseWork.Web/Models/CollectionViewModel.cs
namespace CourseWork.Web.Models
{
    public class CollectionViewModel
    {
        public int Id { get; set; }

        public string AuthorUsername { get; set; }

        public string Title { get; set; }

        public string Description { get; set; }

        public string Theme { get; set; }

        public string Image { get; set; }
    }
}

CourseWork/CourseWork.Web/Models/Collections/CollectionViewModel.cs
namespace CourseWork.Web.Models.Collections
{
    public class CollectionViewModel
    {
        public CollectionViewModel()
        {
            Id = 0;
            Author = string.Empty;
            Title = string.Empty;
            Description = string.Empty;
            Theme = string.Empty;
            Image = string.Empty;
            ImageHeight = 0;
            ImageWidth = 0;
        }

        public int Id { get; set; }

        public string Author { get; set; }

        public string Title { get; set; }

        public string Description { get; set; }

        public string Theme { get; set; }

        public string Image { get; set; }

        public int ImageHeight { get; set; }

        public int ImageWidth { get; set; }
    }
}

CourseWork/CourseWork.Web/Models/Collections/CollectionsViewModel.cs
using CourseWork.Core;
using System.Collections.Generic;

namespace CourseWork.Web.Models.Collections
{
    public class CollectionsViewModel
    {
        public CollectionsViewModel()
        {
            Collections = new List<CollectionViewModel>();
        }

        public IEnumerable<CollectionViewModel> Collections { get; set; }
    }
}

CourseWork/CourseWork.Web/Models/Collections/EditCollectionViewModel.cs
using CourseWork.Core;
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;

namespace CourseWork.Web.Models.Collections
{
    public class EditCollectionViewModel
    {
        public EditCollectionViewModel()
        {
            Id = 0;
            Title = string.Empty;
            Decription = string.Empty;
            Theme = 0;
            PossibleThemes = new List<CollectionTheme>();
            Image = string.Empty;
            ImageFile = null;
        }

        public EditCollectionViewModel(Collection collection, IEnumerable<CollectionTheme> possibleThemes)
        {
            Id = collection.Id;
            UserId = collection.UserId;
            Title = collection.Title;
            Decription = collection.Description;
            Theme = collection.CollectionThemeId;
            PossibleThemes = possibleThemes;
            Image = collection.Image;
        }

        public int Id { get; set; }

        public string UserId { get; set; }

        public string Title { get; set; }

        public string Decription { get; set; }

        public int Theme { get; set; }

        public IEnumerable<CollectionTheme> PossibleThemes { get; set; }

        public string Image { get; set; }

        public IFormFile ImageFile { get; set; }
    }
}

CourseWork/CourseWork.Web/Controllers/CollectionsController.cs
using CourseWork.BusinessLogic.Converters;
using CourseWork.BusinessLogic.Services;
using CourseWork.Core;
using CourseWork.Core.Identity;
using CourseWork.Web.Models.Collections;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CourseWork.Web.Controllers
{
    public class CollectionsController : Controller
    {
        private readonly IService<Collection> _collectionService;
        private readonly IService<CollectionTheme> _collectionThemeService;
        private readonly IService<CollectionRequiredFields> _collectionRequiredFields;
        private readonly IService<ImageSize> _imageSizeService;
        private readonly IConverter<IFormFile, string> _imageConvert;

        private readonly UserManager<WebUser> _userManager;

        public CollectionsController(IService<Collection> collectionService,
            IService<CollectionTheme> collectionThemeService,
            IService<CollectionRequiredFields> collectionRequiredFields,
            IService<ImageSize> imageSizeService,
            IConverter<IFormFile, string> imageConvert,
            UserManager<WebUser> userManager)
        {
            _collectionService = collectionService;
            _collectionThemeService = collectionThemeService;
            _collectionRequiredFields = collectionRequiredFields;
            _imageSizeService = imageSizeService;
            _imageConvert = imageConvert;

            _userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string userId = null)
        {
            if (string.IsNullOrEmpty(userId))
            {
                return await SeeCommonCollections();
            }
            else
            {
                return await SeeUserCollections(userId);
            }
        }

        private async Task<IActionResult> SeeCommonCollections()
        {
            var collectionsRes = await _collectionService.SelectAsync();
            var themesRes = await _collectionThemeService.SelectAsync();
            var sizesRes = await _imageSizeService.SelectAsync();
            if (!collectionsRes.Successfully || !themesRes.Successfully || !sizesRes.Successfully)
            {
                return BadRequest();
            }

            List<CollectionViewModel> collectionViewModels = new List<CollectionViewModel>();
            foreach (var collection in collectionsRes.Value)
            {
                collectionViewModels.Add(new CollectionViewModel
                {
                    Id = collection.Id,
                    Title = collection.Title,
                    Author = (await _userManager.FindByIdAsync(collection.UserId)).UserName,
                    Description = collection.Description,
                    Theme = themesRes.Value.First(item => item.Id == collection.CollectionThemeId).Theme,
                    Image = "data:image/png;base64," + collection.Image,
                    ImageHeight = sizesRes.Value.First(item => item.CollectionId == collection.Id).Height,
                    ImageWidth = sizesRes.Value.First(item => item.CollectionId == collection.Id).Width,
                });
            }

            return View(new CollectionsViewModel { Collections = collectionViewModels });
        }

        private async Task<IActionResult> SeeUserCollections(string userId)
        {
            var collectionsRes = await _collectionService.SelectAsync();
            var themesRes = await _collectionThemeService.SelectAsync();
            var sizesRes = await _imageSizeService.SelectAsync();
            if (!collectionsRes.Successfully || !themesRes.Successfully || !sizesRes.Successfully)
            {
                return BadRequest();
            }

            List<CollectionViewModel> collectionViewModels = new List<CollectionViewModel>();
            foreach (var collection in collectionsRes.Value.Where(c => c.UserId == userId))
            {
                collectionViewModels.Add(new CollectionViewModel
                {
                    Id = collection.Id,
                    Title = collection.Title,
                    Author = (await _userManager.FindByIdAsync(collection.UserId)).UserName,
                    Description = collection.Description,
                    Theme = themesRes.Value.First(item => item.Id == collection.CollectionThemeId).Theme,
                    Image = "data:image/png;base64," + collection.Image,
                    ImageHeight = sizesRes.Value.First(item => item.CollectionId == collection.Id).Height,
                    ImageWidth = sizesRes.Value.First(item => item.CollectionId == collection.Id).Width,
                });
            }

            return View(new CollectionsViewModel { Collections = collectionViewModels });
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var themes = await _collectionThemeService.SelectAsync();
            if (!themes.Successfully)
            {
                return BadRequest();
            }
            else
            {
                return View(new CreateCollectionViewModel { PossibleThemes = themes.Value });
            }
        }

        public async Task<IActionResult> Create([Bind] CreateCollectionViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var collection = new Collection
                {
                    UserId = _userManager.GetUserId(User),
                    Description = viewModel.Decription,
                    Image = _imageConvert.Convert(viewModel.ImageFile),
                    Title = viewModel.Title,
                    CollectionThemeId = viewModel.Theme,
                };
                var collectionRes = await _collectionService.InsertAsync(collection);
                var imageRes = await _imageSizeService.InsertAsync(new ImageSize(0, collection.Id, 150, 150));
                var fieldsRes = await _collectionRequiredFields.InsertAsync(viewModel.ConvertToRequired(collection.Id));
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int collectionId)
        {
            var themes = await _collectionThemeService.SelectAsync();
            var collections = await _collectionService.SelectAsync();
            if (!themes.Successfully || !collections.Successfully)
            {
                return BadRequest();
            }

            var collection = collections.Value.FirstOrDefault(c => c.Id == collectionId);
            if (collection is null)
                return BadRequest();

            return View(new EditCollectionViewModel(collection, themes.Value));
        }

        [HttpPost]
        public async Task<IActionResult> Edit([Bind] EditCollectionViewModel viewModel)
        {
            Collection collection = new Collection
            {
                Id = viewModel.Id,
                UserId = viewModel.UserId,
                CollectionThemeId = viewModel.Theme,
                Description = viewModel.Decription,
                Title = viewModel.Title,
                Image = _imageConvert.Convert(viewModel.ImageFile),
            };

            var collections = await _collectionService.SelectAsync();
            if (!collections.Successfully)
            {
                return BadRequest();
            }

            var bdCollection = collections.Value.FirstOrDefault(c => c.Id == collection.Id);
            if (bdCollection is null)
            {
                return BadRequest();
            }
            bdCollection.Update(collection);
            var res = await _collectionService.UpdateAsync(bdCollection);

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int collectionId)
        {
            var collections = await _collectionService.SelectAsync();
            if (!collections.Successfully)
                return BadRequest();

            var collection = collections.Value.FirstOrDefault(c => c.Id == collectionId);
            if (collection == default)
                return BadRequest();

            var res = await _collectionService.DeleteAsync(collection);
            return RedirectToAction(nameof(Index));
        }
    }
}

CourseWork/CourseWork.Web/Controllers/ItemsController.cs
using CourseWork.BusinessLogic.Services;
using CourseWork.BusinessLogic.StaticServices;
using CourseWork.Core;
using CourseWork.Web.Models.Items;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CourseWork.Web.Controllers
{
    public class ItemsController : Controller
    {
        private readonly SearchItemService _searchService;
        private readonly UserActivityService _userActivityService;
        private readonly ItemFieldsService _itemFieldsService;
        private readonly IService<CollectionItem> _itemService;
        private readonly IService<CollectionRequiredFields> _requiredFieldsService;

        public ItemsController(SearchItemService searchService,
            UserActivityService userActivityService,
            ItemFieldsService itemFieldsService,
            IService<CollectionItem> itemService,
            IService<CollectionRequiredFields> requiredFieldsService)
        {
            _searchService = searchService;
            _userActivityService = userActivityService;
            _itemFieldsService = itemFieldsService;
            _itemService = itemService;
            _requiredFieldsService = requiredFieldsService;
        }

        public async Task<IActionResult> Index(int collectionId = 0, string searchString = null)
        {
            ItemsViewModel model = new ItemsViewModel();
            IEnumerable<CollectionItem> items = new List<CollectionItem>();
            if (collectionId != 0 && string.IsNullOrEmpty(searchString))
            {
                var serviceRes = await _itemService.SelectAsync();
                var fieldsRes = await _requiredFieldsService.SelectAsync();
                if (!serviceRes.Successfully || !fieldsRes.Successfully)
                {
                    return BadRequest();
                }
                items = serviceRes.Value.Where(i => i.CollectionId == collectionId);
                model.CollectionId = collectionId;
                model.Fields = fieldsRes.Value.First(f => f.CollectionId == collectionId).GetSpecifiedFields();
            }
            else if (collectionId == 0 && !string.IsNullOrEmpty(searchString))
            {
                var serviceRes = await _searchService.SearchItems(searchString);
                if (!serviceRes.Successfully)
                {
                    return BadRequest();
                }
                items = serviceRes.Value;
                model.Fields = new List<string>();
            }

            var likesRes = await _userActivityService.GetLikes();
            var commentsRes = await _userActivityService.GetComments();
            if (!likesRes.Successfully || !commentsRes.Successfully)
            {
                return BadRequest();
            }

            model.Items = items.Select(i => new ItemViewModel
            {
                Id = i.Id,
                Name = i.Name,
                Comments = commentsRes.Value.Count(c => c.CollectionItemId == i.Id),
                Likes = likesRes.Value.Count(l => l.CollectionItemId == i.Id),
            }).ToList();

            return View(model);
        }

        public IActionResult CantCreate()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Create(int collectionId)
        {
            if (collectionId == 0)
            {
                return LocalRedirect("~/Collections/Index");
            }
            var fields = await _requiredFieldsService.SelectAsync();
            if (!fields.Successfully)
            {
                return RedirectToAction(nameof(Index), new { collectionId = collectionId });
            }

            return View(new CreateItemViewModel(collectionId, fields.Value.First(f => f.CollectionId == collectionId)));
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind] CreateItemViewModel viewModel)
        {
            var item = new CollectionItem(0, viewModel.CollectionId, viewModel.Name);
            var itemRes = await _itemService.InsertAsync(item);
            if (!itemRes.Successfully)
            {
                return BadRequest();
            }
            var fields = viewModel.GetFields(item.Id);
            var fieldsRes = await _itemFieldsService.AddFields(item.Id, fields);

            if (!fieldsRes.Successfully)
            {
                return BadRequest();
            }

            return RedirectToAction(nameof(Index), new { collectionId = viewModel.CollectionId });
        }

        public async Task<IActionResult> DeleteItem(int itemId, string returnUrl)
        {
            var items = await _itemService.SelectAsync();
            if (!items.Successfully)
                return BadRequest();

            var item = items.Value.FirstOrDefault(i => i.Id == itemId);
            if (item == default)
                return BadRequest();

            var res = await _itemService.DeleteAsync(item);
            return LocalRedirect(returnUrl);
        }
    }
}

CourseWork/CourseWork.Web/Views/Collections/Create.cshtml
@model CourseWork.Web.Models.Collections.CreateCollectionViewModel
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer

<div class="container mt-5">
    <div class="row justify-content-center align-items-center">
        <div>
            <form asp-controller="Collections" asp-action="Create" method="post" enctype="multipart/form-data">
                <div class="col-sm-12 col-mb-12 col-lg-4">
                    <h3 class="mb-3">@Localizer["ViewTitle"]</h3>
                    <div class="form-group">
                        <label class="form-label" asp-for="@Model.Title">@Localizer["Title"]</label>
                        <input type="text" asp-for="@Model.Title" class="form-control" />
                        <span asp-validation-for="@Model.Title" class="text-danger"></span>
                    </div>
                    <div class="mb-2 form-group">
                        <label class="form-label" asp-for="@Model.Decription">@Localizer["Decription"]</label>
                        <input type="text" asp-for="@Model.Decription" class="form-control" />
                        <span asp-validation-for="@Model.Decription" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label class="form-label" asp-for="@Model.Theme">@Localizer["Theme"]</label>
                        <input type="number" asp-for="@Model.Theme" class="form-control" list="layouts">
                        <datalist id="layouts">
                            @foreach (var item in Model.PossibleThemes)
                            {
                                <option value="@item.Id">@item.Theme</option>
                            }
                        </datalist>
                        <span asp-validation-for="@Model.Theme" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.ImageFile" class="control-label"></label>
                        <input asp-for="@Model.ImageFile" accept="image/*" />
                        <span asp-validation-for="@Model.ImageFile" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label>@Localizer["BooleanFieldNames"]</label>
                    <div class="row">
                        <div class="col-4">
                            <input type="text" asp-for="@Model.Boolean1FieldName" class="form-control" />
                        </div>
                        <div class="col-4">
                            <input type="text" asp-for="@Model.Boolean2FieldName" class="form-control" />
                        </div>
                        <div class="col-4">
                            <input type="text" asp-for="@Model.Boolean3FieldName" class="form-control" />
                        </div>
                    </div>
                    <label>@Localizer["DateFieldNames"]</label>
                    <div class="row">
                        <div class="col-4">
                            <input type="text" asp-for="@Model.Date1FieldName" class="form-control" />
                        </div>
                        <div class="col-4">
                            <input type="text" asp-for="@Model.Date2FieldName" class="form-control" />
                        </div>
                        <div class="col-4">
                            <input type="text" asp-for="@Model.Date3FieldName" class="form-control" />
                        </div>
                    </div>
                    <label>@Localizer["IntFieldNames"]</label>
                    <div class="row">
                        <div class="col-4">
                            <input type="text" asp-for="@Model.Int1FieldName" class="form-control" />
                        </div>
                        <div class="col-4">
                            <input type="text" asp-for="@Model.Int2FieldName" class="form-control" />
                        </div>
                        <div class="col-4">
                            <input type="text" asp-for="@Model.Int3FieldName" class="form-control" />
                        </div>
                    </div>
                    <label>@Localizer["StringFieldNames"]</label>
                    <div class="row">
                        <div class="col-4">
                            <input type="text" asp-for="@Model.String1FieldName" class="form-control" />
                        </div>
                        <div class="col-4">
                            <input type="text" asp-for="@Model.String2FieldName" class="form-control" />
                        </div>
                        <div class="col-4">
                            <input type="text" asp-for="@Model.String3FieldName" class="form-control" />
                        </div>
                    </div>
                    <label>@Localizer["TextFieldNames"]</label>
                    <div class="row">
                        <div class="col-4">
                            <input type="text" asp-for="@Model.Text1FieldName" class="form-control" />
                        </div>
                        <div class="col-4">
                            <input type="text" asp-for="@Model.Text2FieldName" class="form-control" />
                        </div>
                        <div class="col-4">
                            <input type="text" asp-for="@Model.Text3FieldName" class="form-control" />
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">@Localizer["Create"]</button>
            </form>
        </div>
    </div>
</div>

CourseWork/CourseWork.Web/Views/Collections/Edit.cshtml
@model CourseWork.Web.Models.Collections.EditCollectionViewModel
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer

<div class="container mt-5">
    <div class="row justify-content-center align-items-center">
        <div class="col-sm-12 col-mb-12 col-lg-4">
            <form asp-controller="Collections" asp-action="Edit" method="post" enctype="multipart/form-data">
                <h3 class="mb-3">@Localizer["ViewTitle"]</h3>
                <input type="hidden" asp-for="@Model.Id"/>
                <input type="hidden" asp-for="@Model.UserId"/>

                <div class="form-group">
                    <label class="form-label" asp-for="@Model.Title">@Localizer["Title"]</label>
                    <input type="text" asp-for="@Model.Title" class="form-control" />
                    <span asp-validation-for="@Model.Title" class="text-danger"></span>
                </div>
                <div class="mb-2 form-group">
                    <label class="form-label" asp-for="@Model.Decription">@Localizer["Decription"]</label>
                    <input type="text" asp-for="@Model.Decription" class="form-control" />
                    <span asp-validation-for="@Model.Decription" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label class="form-label" asp-for="@Model.Theme">@Localizer["Theme"]</label>
                    <input type="number" asp-for="@Model.Theme" class="form-control" list="layouts">
                    <datalist id="layouts">
                        @foreach (var item in Model.PossibleThemes)
                        {
                            <option value="@item.Id">@item.Theme</option>
                        }
                    </datalist>
                    <span asp-validation-for="@Model.Theme" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.ImageFile" class="control-label"></label>
                    <input asp-for="@Model.ImageFile" accept="image/*" />
                    <span asp-validation-for="@Model.ImageFile" class="text-danger"></span>
                </div>
                <button type="submit" class="btn btn-primary">@Localizer["Edit"]</button>
            </form>
        </div>
    </div>
</div>

CourseWork/CourseWork.Web/Views/Collections/Index.cshtml
@model CourseWork.Web.Models.Collections.CollectionsViewModel
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.AspNetCore.Identity

@inject IViewLocalizer Localizer
@inject SignInManager<CourseWork.Core.Identity.WebUser> SignInManager
@inject UserManager<CourseWork.Core.Identity.WebUser> UserManager

<div>
    <div class="row">
        <div class="col-6">@await Html.PartialAsync("_ItemSearch")</div>
        <div class="col-6"><a class="btn btn-primary" asp-controller="Collections" asp-action="Create">@Localizer["Create"]</a></div>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>@Localizer["CollectionImage"]</th>
                <th>@Localizer["CollectionTheme"]</th>
                <th>@Localizer["CollectionTitle"]</th>
                <th>@Localizer["CollectionDescription"]</th>
                <th>@Localizer["CollectionAuthor"]</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var collection in Model.Collections)
            {
            <tr>
                <td><img src="@collection.Image" alt="" height="@collection.ImageHeight" width="@collection.ImageWidth" /></td>
                <td>@Html.DisplayFor(item => collection.Theme)</td>
                <td>@Html.DisplayFor(item => collection.Title)</td>
                <td>@Html.DisplayFor(item => collection.Description)</td>
                <td>@Html.DisplayFor(item => collection.Author)</td>
                <td>
                    <a asp-action="Index" asp-controller="Items" asp-route-collectionId="@collection.Id">@Localizer["Select"]</a>
                    @if (SignInManager.IsSignedIn(User) || User.IsInRole("admin") || UserManager.GetUserName(User) == collection.Author)
                    {
                        <a asp-action="Edit" asp-controller="Collections" asp-route-collectionId="@collection.Id">@Localizer["Edit"]</a>
                        <a asp-action="Delete" asp-controller="Collections" asp-route-collectionId="@collection.Id">@Localizer["Delete"]</a>
                    }
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>